# Generated by Django 3.0.8 on 2020-07-23 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('q_description', models.CharField(default='Sample question', max_length=500)),
                ('q_type', models.CharField(choices=[('Behavior Question', 'Behavior Question'), ('Technique Question', 'Technique Question')], default='Behavior Question', max_length=50)),
                ('needed_expert_review', models.BooleanField(default=False)),
                ('is_expert_reviewed', models.BooleanField(default=False)),
                ('needed_ai_review', models.BooleanField(default=False)),
                ('is_ai_reviewed', models.BooleanField(default=False)),
                ('comments', models.TextField(default='No comments yet')),
                ('expert_score', models.FloatField(default=10.0)),
                ('expert_review_categories', models.CharField(default='Positive Attitude,Communication,Detail Oriented,Team Spirit,Stress Tolerance', max_length=500)),
                ('expert_category_score', models.CharField(default='10,10,10,10,10', max_length=500)),
                ('ai_score', models.FloatField(default=10.0)),
                ('ai_review_categories', models.CharField(default='Positive Attitude,Communication,Detail Oriented,Team Spirit,Stress Tolerance', max_length=500)),
                ('ai_category_score', models.CharField(default='10,10,10,10,10', max_length=500)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
