# Generated by Django 3.0.5 on 2020-05-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_video_is_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comments',
            field=models.TextField(default='No comments yet'),
        ),
        migrations.AddField(
            model_name='video',
            name='score',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.TextField(default='Good job'),
        ),
    ]
