# Generated by Django 3.0.5 on 2020-05-05 22:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videos', '0007_auto_20200505_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='reviewer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewed_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
