# Generated by Django 3.0.5 on 2020-05-05 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_video_reviewer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='reviewer_id',
            new_name='reviewer',
        ),
    ]
