# Generated by Django 3.0.5 on 2020-05-14 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_auto_20200507_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='is_reviewed',
            new_name='is_expert_reviewed',
        ),
        migrations.AddField(
            model_name='video',
            name='is_ai_reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
