# Generated by Django 3.0.5 on 2020-05-24 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20200518_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='needed_ai_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='needed_expert_review',
            field=models.BooleanField(default=False),
        ),
    ]
