# Generated by Django 3.0.7 on 2020-06-08 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_auto_20200525_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='q_type',
            field=models.CharField(choices=[('Behavior Question', 'Behavior Question'), ('Technique Question', 'Technique Question')], default='Behavior Question', max_length=50),
        ),
    ]
