# Generated by Django 3.0.7 on 2020-06-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_video_q_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='score',
        ),
        migrations.AddField(
            model_name='video',
            name='ai_category_score',
            field=models.CharField(default='10,10', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_review_categories',
            field=models.CharField(default='Positive Attitude,Communication', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='ai_score',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='video',
            name='expert_category_score',
            field=models.CharField(default='10,10', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='expert_review_categories',
            field=models.CharField(default='Positive Attitude,Communication', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='expert_score',
            field=models.FloatField(default=10.0),
        ),
    ]
