# Generated by Django 3.0.7 on 2020-06-14 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20200614_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_review_categories',
            field=models.CharField(default='Positive Attitude,Communication,Detail Oriented,Team Spirit,Stress Tolerance', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='expert_review_categories',
            field=models.CharField(default='Positive Attitude,Communication,Detail Oriented,Team Spirit,Stress Tolerance', max_length=500),
        ),
    ]
