# Generated by Django 3.0.7 on 2020-06-14 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0021_auto_20200614_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ai_category_score',
        ),
        migrations.RemoveField(
            model_name='video',
            name='expert_category_score',
        ),
    ]
