# Generated by Django 3.0.7 on 2020-06-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_auto_20200614_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='ai_category_score',
            field=models.CharField(default='10,10,10,10,10', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='expert_category_score',
            field=models.CharField(default='10,10,10,10,10', max_length=500),
        ),
    ]
