export const GET_VIDEOS = "GET_VIDEOS";
export const DELETE_VIDEO = "DELETE_VIDEOS";
export const ADD_VIDEO = "ADD_VIDEO";
export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGES";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const NEXT_QUESTION = "NEXT_QUESTION";

export const ADD_REVIEWS = "ADD_REVIEWS";
export const GET_UNREVIEWED_VIDEO = "GET_UNREVIEWED_VIDEO";

export const PROFILE_LOADED = "PROFILE_LOADED";
export const PROFILE_UPDATED = "PROFILE_UPDATED";
