# Generated by Django 3.0.5 on 2020-05-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200519_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerinfo',
            name='reviews_count',
            field=models.IntegerField(default=0),
        ),
    ]
