# Generated by Django 3.0.5 on 2020-05-19 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200519_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewerinfo',
            old_name='reviews_count',
            new_name='review_count',
        ),
    ]
