# Generated by Django 3.0.7 on 2020-06-18 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_save_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_video_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
