# Generated by Django 3.0.8 on 2020-07-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='BQ', max_length=300)),
                ('description', models.TextField(default='No description', null=True)),
                ('category', models.CharField(choices=[('Positive Attitude', 'Positive Attitude'), ('Loyalty & Commitment', 'Loyalty & Commitment'), ('Team Player Spirit', 'Team Player Spirit'), ('Leadership', 'Leadership'), ('Pressure Handling', 'Pressure Handling'), ('Self-Motivated', 'Self-Motivated'), ('Strong Work Ethic', 'Strong Work Ethic'), ('Creativity', 'Creativity'), ('Dependable & Reliable', 'Dependable & Reliable'), ('Detail Oriented', 'Detail Oriented'), ('Good Communication', 'Good Communication'), ('Problem Solving', 'Problem Solving')], default='Positive Attitude', max_length=50)),
            ],
        ),
    ]
