# Generated by Django 3.0.5 on 2020-04-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='A Question')),
                ('description', models.TextField(default='No description')),
                ('category', models.CharField(choices=[('Teamwork', 'Teamwork'), ('TimeManagement', 'TimeManagement'), ('Integrity', 'Integrity')], default='Teamwork', max_length=50)),
            ],
        ),
    ]
