# Generated by Django 3.0.5 on 2020-05-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('Positive Attitude', 'Positive Attitude'), ('Loyalty & Commitment', 'Loyalty & Commitment'), ('Team Player Spirit', 'Team Player Spirit'), ('Leadership', 'Leadership'), ('Pressure Handling', 'Pressure Handling'), ('Self-Motivated', 'Self-Motivated'), ('Strong Work Ethic', 'Strong Work Ethic'), ('Creativity', 'Creativity'), ('Dependable & Reliable', 'Dependable & Reliable'), ('Detail Oriented', 'Detail Oriented'), ('Good Communication', 'Good Communication'), ('Problem Solving', 'Problem Solving')], default='Positive Attitude', max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default='No description', null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(default='A Question', max_length=300),
        ),
    ]
